# Czech message translation file for plpython
# Copyright (C) 2012 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
#
# Tomáš Vondra <tv@fuzzy.cz>, 2012, 2013.
msgid ""
msgstr ""
"Project-Id-Version: plpython-cs (PostgreSQL 9.3)\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
<<<<<<< HEAD
"POT-Creation-Date: 2018-07-13 16:48+0000\n"
"PO-Revision-Date: 2018-07-14 00:35+0200\n"
=======
"POT-Creation-Date: 2018-07-13 19:37+0000\n"
"PO-Revision-Date: 2018-07-13 23:53+0200\n"
>>>>>>> REL_11_0
"Last-Translator: Tomas Vondra <tv@fuzzy.cz>\n"
"Language-Team: Czech <info@cspug.cx>\n"
"Language: cs\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"
"X-Generator: Poedit 2.0.7\n"

<<<<<<< HEAD
#: plpy_cursorobject.c:100
=======
#: plpy_cursorobject.c:101
>>>>>>> REL_11_0
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor očekával dotaz nebo plán"

<<<<<<< HEAD
#: plpy_cursorobject.c:176
=======
#: plpy_cursorobject.c:184
>>>>>>> REL_11_0
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor jako druhý argument očekává sekvenci"

<<<<<<< HEAD
#: plpy_cursorobject.c:192 plpy_spi.c:226
=======
#: plpy_cursorobject.c:200 plpy_spi.c:211
>>>>>>> REL_11_0
#, c-format
msgid "could not execute plan"
msgstr "nelze spustit plán"

<<<<<<< HEAD
#: plpy_cursorobject.c:195 plpy_spi.c:229
=======
#: plpy_cursorobject.c:203 plpy_spi.c:214
>>>>>>> REL_11_0
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Očekávána posloupnost %d argument, předáno %d: %s"
msgstr[1] "Očekávána posloupnost %d argumentů, předáno %d: %s"
msgstr[2] "Očekávána posloupnost %d argumentů, předáno %d: %s"

<<<<<<< HEAD
#: plpy_cursorobject.c:350
=======
#: plpy_cursorobject.c:352
>>>>>>> REL_11_0
#, c-format
msgid "iterating a closed cursor"
msgstr "iterování uzavřeného kurzoru"

<<<<<<< HEAD
#: plpy_cursorobject.c:358 plpy_cursorobject.c:423
=======
#: plpy_cursorobject.c:360 plpy_cursorobject.c:426
>>>>>>> REL_11_0
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "iterování kurzoru ve zrušené subtransakci"

<<<<<<< HEAD
#: plpy_cursorobject.c:415
=======
#: plpy_cursorobject.c:418
>>>>>>> REL_11_0
#, c-format
msgid "fetch from a closed cursor"
msgstr "fetch ze zavřeného kurzoru"

<<<<<<< HEAD
#: plpy_cursorobject.c:463 plpy_spi.c:434
=======
#: plpy_cursorobject.c:461 plpy_spi.c:409
>>>>>>> REL_11_0
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "výsledek dotazu má příliš mnoho řádek a nevejde se to Python seznamu"

<<<<<<< HEAD
#: plpy_cursorobject.c:504
=======
#: plpy_cursorobject.c:512
>>>>>>> REL_11_0
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "uzavření kurzoru ve zrušené subtransakci"

<<<<<<< HEAD
#: plpy_elog.c:127 plpy_elog.c:128 plpy_plpymodule.c:548
=======
#: plpy_elog.c:127 plpy_elog.c:128 plpy_plpymodule.c:559
>>>>>>> REL_11_0
#, c-format
msgid "%s"
msgstr "%s"

<<<<<<< HEAD
#: plpy_exec.c:140
=======
#: plpy_exec.c:142
>>>>>>> REL_11_0
#, c-format
msgid "unsupported set function return mode"
msgstr "nepodporovaný návratový mód funkce vracející tabulku"

<<<<<<< HEAD
#: plpy_exec.c:141
=======
#: plpy_exec.c:143
>>>>>>> REL_11_0
#, c-format
msgid ""
"PL/Python set-returning functions only support returning one value per call."
msgstr ""
"PL/Python funkce vracející tabulku podporují pouze vracení jedné hodnoty pro "
"každé volání."

<<<<<<< HEAD
#: plpy_exec.c:154
=======
#: plpy_exec.c:156
>>>>>>> REL_11_0
#, c-format
msgid "returned object cannot be iterated"
msgstr "přes vrácený objekt nelze iterovat"

<<<<<<< HEAD
#: plpy_exec.c:155
=======
#: plpy_exec.c:157
>>>>>>> REL_11_0
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "PL/Python funkce vracející tabulku musí vracet iterovatelný objekt."

<<<<<<< HEAD
#: plpy_exec.c:169
=======
#: plpy_exec.c:171
>>>>>>> REL_11_0
#, c-format
msgid "error fetching next item from iterator"
msgstr "chyba při načítání další položky z iterátoru"

<<<<<<< HEAD
#: plpy_exec.c:210
=======
#: plpy_exec.c:214
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "PL/Python procedura nevrátila hodnotu None"

#: plpy_exec.c:218
>>>>>>> REL_11_0
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "PL/Python funkce s návratovým typem \"void\" nevrátila hodnotu None"

<<<<<<< HEAD
#: plpy_exec.c:379 plpy_exec.c:405
=======
#: plpy_exec.c:374 plpy_exec.c:400
>>>>>>> REL_11_0
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "neočekávaná návratová hodnota z trigger procedury"

<<<<<<< HEAD
#: plpy_exec.c:380
=======
#: plpy_exec.c:375
>>>>>>> REL_11_0
#, c-format
msgid "Expected None or a string."
msgstr "Očekáváno None nebo řetězec."

<<<<<<< HEAD
#: plpy_exec.c:395
=======
#: plpy_exec.c:390
>>>>>>> REL_11_0
#, c-format
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"PL/Python trigger funkce vrátila \"MODIFY\" v DELETE triggeru -- ignorováno"

<<<<<<< HEAD
#: plpy_exec.c:406
=======
#: plpy_exec.c:401
>>>>>>> REL_11_0
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Očekáváno None, \"OK\", \"SKIP\", nebo \"MODIFY\"."

<<<<<<< HEAD
#: plpy_exec.c:487
=======
#: plpy_exec.c:451
>>>>>>> REL_11_0
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "volání PyList_SetItem() selhalo během vytváření argumentů"

<<<<<<< HEAD
#: plpy_exec.c:491
=======
#: plpy_exec.c:455
>>>>>>> REL_11_0
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "volání PyDict_SetItemString() selhalo během přípravy argumentů"

<<<<<<< HEAD
#: plpy_exec.c:503
=======
#: plpy_exec.c:467
>>>>>>> REL_11_0
#, c-format
msgid ""
"function returning record called in context that cannot accept type record"
msgstr ""
"funkce vracející záznam byla zavolána z kontextu, který neumožňuje přijetí "
"záznamu"

<<<<<<< HEAD
#: plpy_exec.c:719
=======
#: plpy_exec.c:684
>>>>>>> REL_11_0
#, c-format
msgid "while creating return value"
msgstr "během vytváření návratové hodnoty"

<<<<<<< HEAD
#: plpy_exec.c:743
#, c-format
msgid "could not create new dictionary while building trigger arguments"
msgstr "během vytváření argumentů triggeru nelze vytvářet nový slovník"

#: plpy_exec.c:931
=======
#: plpy_exec.c:909
>>>>>>> REL_11_0
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] smazáno, nelze modifikovat řádek"

<<<<<<< HEAD
#: plpy_exec.c:936
=======
#: plpy_exec.c:914
>>>>>>> REL_11_0
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] není slovník"

<<<<<<< HEAD
#: plpy_exec.c:963
=======
#: plpy_exec.c:941
>>>>>>> REL_11_0
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "TD[\"new\"] klíč slovníku na pozici %d není řetězec"

<<<<<<< HEAD
#: plpy_exec.c:970
=======
#: plpy_exec.c:948
>>>>>>> REL_11_0
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"klíč \"%s\" nalezený v TD[\"new\"] neexistuje jako sloupec v triggering řádku"

<<<<<<< HEAD
#: plpy_exec.c:975
=======
#: plpy_exec.c:953
>>>>>>> REL_11_0
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "nelze nastavit systémový atribut \"%s\""

<<<<<<< HEAD
#: plpy_exec.c:1046
=======
#: plpy_exec.c:1011
>>>>>>> REL_11_0
#, c-format
msgid "while modifying trigger row"
msgstr "během modifikace řádku triggeru"

<<<<<<< HEAD
#: plpy_exec.c:1107
=======
#: plpy_exec.c:1072
>>>>>>> REL_11_0
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "vynucené ukončení subtransakce která nebyla dokončena"

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "v session je načteno několik Python knihoven"

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Pouze jedna major verze Pythonu může být použita v jedné session."

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr "nezachycená chyba v inicializaci"

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr "nepodařilo se naimportovat \"__main__\" modul"

<<<<<<< HEAD
#: plpy_main.c:170
#, c-format
msgid "could not create globals"
msgstr "nepodařilo se vytvořit globals"

=======
>>>>>>> REL_11_0
#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr "nepodařilo se inicializovat globální proměnné (globals)"

<<<<<<< HEAD
#: plpy_main.c:387
=======
#: plpy_main.c:399
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "PL/Python procedura \"%s\""

#: plpy_main.c:402
>>>>>>> REL_11_0
#, c-format
msgid "PL/Python function \"%s\""
msgstr "PL/Python funkce \"%s\""

<<<<<<< HEAD
#: plpy_main.c:394
=======
#: plpy_main.c:410
>>>>>>> REL_11_0
#, c-format
msgid "PL/Python anonymous code block"
msgstr "PL/Python anonymní blok kódu"

<<<<<<< HEAD
#: plpy_plpymodule.c:181 plpy_plpymodule.c:184
=======
#: plpy_plpymodule.c:192 plpy_plpymodule.c:195
>>>>>>> REL_11_0
#, c-format
msgid "could not import \"plpy\" module"
msgstr "nepodařilo se naimportovat \"plpy\" modul"

<<<<<<< HEAD
#: plpy_plpymodule.c:199
#, c-format
msgid "could not create the spiexceptions module"
msgstr "nepodařilo se vytvořit spiexceptions modul"

#: plpy_plpymodule.c:207
=======
#: plpy_plpymodule.c:210
>>>>>>> REL_11_0
#, c-format
msgid "could not create the spiexceptions module"
msgstr "nepodařilo se vytvořit spiexceptions modul"

<<<<<<< HEAD
#: plpy_plpymodule.c:236
#, c-format
msgid "could not create exception \"%s\""
msgstr "nepodařilo se vygenerovat výjimku \"%s\""

#: plpy_plpymodule.c:271 plpy_plpymodule.c:275
=======
#: plpy_plpymodule.c:218
#, c-format
msgid "could not add the spiexceptions module"
msgstr "nepodařilo se naimportovat \"__main__\" modul"

#: plpy_plpymodule.c:286
>>>>>>> REL_11_0
#, c-format
msgid "could not generate SPI exceptions"
msgstr "nepodařilo se vygenerovat SPI výjimky"

<<<<<<< HEAD
#: plpy_plpymodule.c:443
=======
#: plpy_plpymodule.c:454
>>>>>>> REL_11_0
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "nepodařilo se rozbalit argumenty v plpy.elog"

<<<<<<< HEAD
#: plpy_plpymodule.c:452
msgid "could not parse error message in plpy.elog"
msgstr "nepodařilo se naparsovat chybovou hlášku v plpy.elog"

#: plpy_plpymodule.c:469
=======
#: plpy_plpymodule.c:463
msgid "could not parse error message in plpy.elog"
msgstr "nepodařilo se naparsovat chybovou hlášku v plpy.elog"

#: plpy_plpymodule.c:480
>>>>>>> REL_11_0
#, c-format
msgid "argument 'message' given by name and position"
msgstr "argument 'message' zadán jménem a pozicí"

<<<<<<< HEAD
#: plpy_plpymodule.c:496
=======
#: plpy_plpymodule.c:507
>>>>>>> REL_11_0
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "'%s' je neplatný keyword argument pro tuto funkci"

<<<<<<< HEAD
#: plpy_plpymodule.c:507 plpy_plpymodule.c:513
=======
#: plpy_plpymodule.c:518 plpy_plpymodule.c:524
>>>>>>> REL_11_0
#, c-format
msgid "invalid SQLSTATE code"
msgstr "chybný SQLSTATE kód"

<<<<<<< HEAD
#: plpy_procedure.c:228
=======
#: plpy_procedure.c:230
>>>>>>> REL_11_0
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr ""
"funkce pro obsluhu triggerů mohou být volané pouze prostřednictvím triggerů"

<<<<<<< HEAD
#: plpy_procedure.c:233
=======
#: plpy_procedure.c:234
>>>>>>> REL_11_0
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python funkce nemohou vracet typ %s"

<<<<<<< HEAD
#: plpy_procedure.c:314
=======
#: plpy_procedure.c:312
>>>>>>> REL_11_0
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python funkce nepodporují typ %s"

<<<<<<< HEAD
#: plpy_procedure.c:410
=======
#: plpy_procedure.c:402
>>>>>>> REL_11_0
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "nelze zkompiloval PL/Python funkci \"%s\""

<<<<<<< HEAD
#: plpy_procedure.c:413
=======
#: plpy_procedure.c:405
>>>>>>> REL_11_0
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "nelze zkompiloval anonymní PL/Python blok"

#: plpy_resultobject.c:150 plpy_resultobject.c:176 plpy_resultobject.c:202
#, c-format
msgid "command did not produce a result set"
msgstr "příkaz nevrátil žádný výsledek"

<<<<<<< HEAD
#: plpy_spi.c:59
=======
#: plpy_spi.c:60
>>>>>>> REL_11_0
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "druhý argument pro plpy.prepare musí být posloupnost"

<<<<<<< HEAD
#: plpy_spi.c:115
=======
#: plpy_spi.c:104
>>>>>>> REL_11_0
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: název typu na pozici %d není řetězec"

<<<<<<< HEAD
#: plpy_spi.c:191
=======
#: plpy_spi.c:176
>>>>>>> REL_11_0
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute očekávala dotaz nebo plán"

<<<<<<< HEAD
#: plpy_spi.c:210
=======
#: plpy_spi.c:195
>>>>>>> REL_11_0
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute jako druhý argument očekává posloupnost"

<<<<<<< HEAD
#: plpy_spi.c:335
=======
#: plpy_spi.c:305
>>>>>>> REL_11_0
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "volání SPI_execute_plan selhalo: %s"

<<<<<<< HEAD
#: plpy_spi.c:377
=======
#: plpy_spi.c:347
>>>>>>> REL_11_0
#, c-format
msgid "SPI_execute failed: %s"
msgstr "volání SPI_execute selhalo: %s"

#: plpy_subxactobject.c:122
#, c-format
msgid "this subtransaction has already been entered"
msgstr "tato subtransakce již byla zahájena"

#: plpy_subxactobject.c:128 plpy_subxactobject.c:186
#, c-format
msgid "this subtransaction has already been exited"
msgstr "tato subtransakce již byla dokončena"

#: plpy_subxactobject.c:180
#, c-format
msgid "this subtransaction has not been entered"
msgstr "tato subtransakce nebyla zahájena"

#: plpy_subxactobject.c:192
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "nenalezena subtransakce k ukončení"

<<<<<<< HEAD
#: plpy_typeio.c:292
#, c-format
msgid "could not create new dictionary"
msgstr "nepodařilo se vytvořit nový slovník"

#: plpy_typeio.c:560
=======
#: plpy_typeio.c:591
>>>>>>> REL_11_0
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "nepodařilo se naimportovat modul pro Decimal constructor"

<<<<<<< HEAD
#: plpy_typeio.c:564
=======
#: plpy_typeio.c:595
>>>>>>> REL_11_0
#, c-format
msgid "no Decimal attribute in module"
msgstr "modul nemá žádný Decimal atribut"

<<<<<<< HEAD
#: plpy_typeio.c:570
=======
#: plpy_typeio.c:601
>>>>>>> REL_11_0
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "konverze z numeric na Decimal selhala"

<<<<<<< HEAD
#: plpy_typeio.c:773
=======
#: plpy_typeio.c:908
>>>>>>> REL_11_0
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "nepodařilo se vytvořit bytovou reprezentaci Python objektu"

<<<<<<< HEAD
#: plpy_typeio.c:882
=======
#: plpy_typeio.c:1056
>>>>>>> REL_11_0
#, c-format
msgid "could not create string representation of Python object"
msgstr "nepodařilo se vytvořit řetězcovou reprezentaci Python objektu"

<<<<<<< HEAD
#: plpy_typeio.c:893
=======
#: plpy_typeio.c:1067
>>>>>>> REL_11_0
#, c-format
msgid ""
"could not convert Python object into cstring: Python string representation "
"appears to contain null bytes"
msgstr ""
"nepodařilo se převést Python objekt na cstring: zdá se že řetězcová "
"reprezentace Python objektu obsahuje null byty"

<<<<<<< HEAD
#: plpy_typeio.c:950
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "chybný literál záznamu: \"%s\""

#: plpy_typeio.c:951
#, c-format
msgid "Missing left parenthesis."
msgstr "Chybějící levá závorka."

#: plpy_typeio.c:952 plpy_typeio.c:1390
#, c-format
msgid ""
"To return a composite type in an array, return the composite type as a "
"Python tuple, e.g., \"[('foo',)]\"."
msgstr ""
"Pro vrácení kompozitního typu v poli, vracejte kompozitní typ jako Python "
"tuple, e.g., \"[('foo',)]\"."

#: plpy_typeio.c:1001
=======
#: plpy_typeio.c:1176
>>>>>>> REL_11_0
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "počet dimenzí pole překračuje povolené maximum (%d)"

<<<<<<< HEAD
#: plpy_typeio.c:1005
=======
#: plpy_typeio.c:1180
>>>>>>> REL_11_0
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "nelze určit délku posloupnosti pro návratovou hodnotu funkce"

<<<<<<< HEAD
#: plpy_typeio.c:1008 plpy_typeio.c:1012
=======
#: plpy_typeio.c:1183 plpy_typeio.c:1187
>>>>>>> REL_11_0
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "velikost pole překračuje povolené maximum"

<<<<<<< HEAD
#: plpy_typeio.c:1038
=======
#: plpy_typeio.c:1213
>>>>>>> REL_11_0
#, c-format
msgid ""
"return value of function with array return type is not a Python sequence"
msgstr ""
"návratová hodnota funkce s návratovým typem pole není Python posloupnost "
"(sequence)"

<<<<<<< HEAD
#: plpy_typeio.c:1091
=======
#: plpy_typeio.c:1259
>>>>>>> REL_11_0
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr "chybná délka vnitční sekvence: má délku %d, ale očekáváno bylo %d"

<<<<<<< HEAD
#: plpy_typeio.c:1093
=======
#: plpy_typeio.c:1261
>>>>>>> REL_11_0
#, c-format
msgid ""
"To construct a multidimensional array, the inner sequences must all have the "
"same length."
msgstr ""
"Pro vytvoření vícerozměrného pole musí mít včechny vnitřní sekvence stejnou "
"délku."

<<<<<<< HEAD
#: plpy_typeio.c:1213
=======
#: plpy_typeio.c:1340
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "chybný literál záznamu: \"%s\""

#: plpy_typeio.c:1341
#, c-format
msgid "Missing left parenthesis."
msgstr "Chybějící levá závorka."

#: plpy_typeio.c:1342 plpy_typeio.c:1543
#, c-format
msgid ""
"To return a composite type in an array, return the composite type as a "
"Python tuple, e.g., \"[('foo',)]\"."
msgstr ""
"Pro vrácení kompozitního typu v poli, vracejte kompozitní typ jako Python "
"tuple, e.g., \"[('foo',)]\"."

#: plpy_typeio.c:1389
>>>>>>> REL_11_0
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "klíč \"%s\" nenalezen v mapování"

<<<<<<< HEAD
#: plpy_typeio.c:1214
=======
#: plpy_typeio.c:1390
>>>>>>> REL_11_0
#, c-format
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"Pro vrácení hodnoty null ve sloupci, přidejte do mapování hodnotu None s "
"klíčem pojmenovaným jako sloupec."

<<<<<<< HEAD
#: plpy_typeio.c:1265
=======
#: plpy_typeio.c:1443
>>>>>>> REL_11_0
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "délka vrácené posloupnosti neodpovídala počtu sloupců v řádku"

<<<<<<< HEAD
#: plpy_typeio.c:1388
=======
#: plpy_typeio.c:1541
>>>>>>> REL_11_0
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "atribut \"%s\" v Python objektu neexistuje"

<<<<<<< HEAD
#: plpy_typeio.c:1391
=======
#: plpy_typeio.c:1544
>>>>>>> REL_11_0
#, c-format
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"Pro vrácení null ve sloupci, nechť vracený objekt má atribut pojmenovaný po "
"sloupcis hodnotou None."

<<<<<<< HEAD
#: plpy_util.c:36
=======
#: plpy_util.c:35
>>>>>>> REL_11_0
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "nelze převést Python Unicode objekt na byty"

<<<<<<< HEAD
#: plpy_util.c:42
=======
#: plpy_util.c:41
>>>>>>> REL_11_0
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "nepodařilo se získat byty z kódovaného řetězce"

<<<<<<< HEAD
#~ msgid "PL/Python procedure did not return None"
#~ msgstr "PL/Python procedura nevrátila hodnotu None"

#~ msgid "PL/Python procedure \"%s\""
#~ msgstr "PL/Python procedura \"%s\""
=======
#~ msgid "could not create new dictionary while building trigger arguments"
#~ msgstr "během vytváření argumentů triggeru nelze vytvářet nový slovník"
>>>>>>> REL_11_0

#~ msgid ""
#~ "This session has previously used Python major version %d, and it is now "
#~ "attempting to use Python major version %d."
#~ msgstr ""
#~ "Tato session již dříve používala Python s hlavní verzí %d, a nyní se "
#~ "pokouší použít Python s hlavní verzí %d."

#~ msgid "Start a new session to use a different Python major version."
#~ msgstr "Spouští se nová session pro použití jiné hlavní verze Pythonu."

<<<<<<< HEAD
=======
#~ msgid "could not create globals"
#~ msgstr "nepodařilo se vytvořit globals"

>>>>>>> REL_11_0
#~ msgid "plan.status takes no arguments"
#~ msgstr "plan.status nepřijímá žádné argumenty"

#~ msgid "could not create the base SPI exceptions"
#~ msgstr "nepodařilo se vygenerovat základní SPI výjimky"

#~ msgid "plpy.prepare does not support composite types"
#~ msgstr "plpy.prepare nepodporuje složené typy"

#~ msgid "unrecognized error in PLy_spi_execute_fetch_result"
#~ msgstr "nerozpoznaná chyba v PLy_spi_execute_fetch_result"

<<<<<<< HEAD
=======
#~ msgid "could not create new dictionary"
#~ msgstr "nepodařilo se vytvořit nový slovník"

>>>>>>> REL_11_0
#~ msgid "PL/Python does not support conversion to arrays of row types."
#~ msgstr "PL/Python nepodporuje konverzi na pole řádkových typů."

#~ msgid "cannot convert multidimensional array to Python list"
#~ msgstr "vícerozměrné pole nelze převést na Python seznam (list)"

#~ msgid "PL/Python only supports one-dimensional arrays."
#~ msgstr "PL/Python podporuje pouze jednorozměrná pole."

#~ msgid "could not create new Python list"
#~ msgstr "nelze vytvořit nový Python seznam"

#~ msgid "could not initialize plpy"
#~ msgstr "nepodařilo se inicializovat plpy"
